#!/bin/bash

# $1: suspension name, like PR3

date_directory=`date +%Y%m%d`
mkdir -p ../$1/TF/Measurements/$date_directory

for ii in TML TMP TMY
do
    echo "open" >tmp
    echo "restore "../$1/TF/Templates/$1_$ii"_exc.xml" >>tmp
    echo "run -w" >>tmp
    echo "save "../$1/TF/Measurements/$date_directory/$1_$ii"_exc_"`date +%y%m%d_%s`".xml" >> tmp
    echo "quit" >> tmp

    echo "=== Running "$1_$ii"_exc.xml ==="
    diag < tmp
done


